'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AdminShell } from '@/components/admin-shell';
import { Icon } from '@/components/icon';

type ImageRecord = { id: string; category: string; title: string | null; alt_text: string; image_url: string };
const categories = ['exterior', 'rooms', 'restaurant', 'gym_spa', 'meeting_hall', 'other'];

export default function GalleryPage() {
  const [images, setImages] = useState<ImageRecord[]>([]); const [category, setCategory] = useState('all'); const [file, setFile] = useState<File | null>(null); const [altText, setAltText] = useState(''); const [title, setTitle] = useState(''); const [uploadCategory, setUploadCategory] = useState('other'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false);
  async function load() { setLoading(true); const response = await fetch('/api/admin/gallery'); const data = await response.json(); if (!response.ok) setError(data.error || 'Unable to load gallery.'); else setImages(data.images); setLoading(false); }
  useEffect(() => { load(); }, []);
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) return setError('Choose an image first.'); setUploading(true); const form = new FormData(); form.set('file', file); form.set('altText', altText); form.set('title', title); form.set('category', uploadCategory); const response = await fetch('/api/admin/gallery', { method: 'POST', body: form }); const data = await response.json(); setUploading(false); if (!response.ok) return setError(data.error || 'Unable to upload image.'); setImages((current) => [data.image, ...current]); setFile(null); setAltText(''); setTitle(''); setError(''); }
  async function remove(id: string) { if (!window.confirm('Delete this image from the gallery?')) return; const response = await fetch(`/api/admin/gallery/${id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) return setError(data.error || 'Unable to delete image.'); setImages((current) => current.filter((image) => image.id !== id)); }
  const visible = category === 'all' ? images : images.filter((image) => image.category === category);
  return <AdminShell><div className="page-wrap"><div className="page-heading"><div><p className="eyebrow">Content library</p><h1>Gallery<span>.</span></h1><p className="lede">Keep the hotel’s visual story organized and ready to publish.</p></div></div>{error && <p className="form-error admin-inline-error" role="alert">{error}</p>}<section className="panel gallery-upload-panel"><form onSubmit={upload} className="gallery-upload-form"><label>Image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} required /></label><label>Alt text<input value={altText} onChange={(event) => setAltText(event.target.value)} placeholder="Describe this image" required /></label><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Optional title" /></label><label>Category<select value={uploadCategory} onChange={(event) => setUploadCategory(event.target.value)}>{categories.map((item) => <option key={item} value={item}>{item.replace('_', ' ')}</option>)}</select></label><button className="primary-button" disabled={uploading}>{uploading ? 'Uploading…' : 'Upload image'}</button></form></section><div className="filter-tabs gallery-filters"><button className={`filter ${category === 'all' ? 'active' : ''}`} onClick={() => setCategory('all')}>All <b>{images.length}</b></button>{categories.map((item) => <button className={`filter ${category === item ? 'active' : ''}`} onClick={() => setCategory(item)} key={item}>{item.replace('_', ' ')} <b>{images.filter((image) => image.category === item).length}</b></button>)}</div>{loading ? <div className="panel empty-state">Loading gallery…</div> : visible.length === 0 ? <div className="panel empty-state">No uploaded images in this category yet.</div> : <div className="gallery-grid live-gallery-grid">{visible.map((image) => <article className="gallery-card live-gallery-card" key={image.id}><div className="gallery-visual" style={{ backgroundImage: `url(${image.image_url})` }}><span>{image.category.replace('_', ' ')}</span></div><div className="gallery-card-footer"><span><strong>{image.title || image.alt_text}</strong><small>{image.alt_text}</small></span><button className="row-more" onClick={() => remove(image.id)} aria-label={`Delete ${image.title || image.alt_text}`}><Icon name="more" size={16} /></button></div></article>)}</div>}</div></AdminShell>;
}
