import Link from 'next/link';
import { AdminShell } from '@/components/admin-shell';
import { Icon } from '@/components/icon';
import { getDashboardData } from '@/lib/server/dashboard';

function KpiIcon({ type }: { type: string }) { return <div className={`kpi-icon ${type}`}><Icon name={type === 'arrival' || type === 'departure' ? 'calendar' : type === 'revenue' ? 'trend' : 'bed'} size={19} /></div>; }

export default async function AdminOverview() {
  const live = await getDashboardData();
  const kpis = [['Occupancy', `${live.occupancy}%`, `${live.occupiedRooms} of ${live.totalRooms} rooms occupied`, 'occupancy'], ['Today’s arrivals', String(live.arrivals.length), 'From current reservations', 'arrival'], ['Today’s departures', String(live.departures), 'Checkout by 12:00', 'departure'], ['Today’s revenue', `ETB ${Number(live.revenue).toLocaleString()}`, 'From recorded bookings', 'revenue']];
  return <AdminShell><div className="page-wrap">
    <div className="page-heading"><div><p className="eyebrow">Hotel operations · live</p><h1>Good morning<span>.</span></h1><p className="lede">Here’s what’s happening across Abebe Zeleke today.</p></div><Link href="/admin/bookings?new=true" className="primary-button"><Icon name="plus" size={17} /> New booking</Link></div>
    <section className="kpi-grid" aria-label="Live hotel performance">{kpis.map(([label, value, detail, icon]) => <div className="kpi-card" key={label}><div className="kpi-top"><span>{label}</span><KpiIcon type={icon} /></div><strong className="kpi-value">{value}</strong><span className="kpi-detail"><Icon name="trend" size={13} /> {detail}</span></div>)}</section>
    <div className="content-grid"><section className="panel arrivals-panel"><div className="panel-heading"><div><h2>Today’s arrivals</h2><p>{live.arrivals.length} guests expected · live from bookings</p></div><Link href="/admin/bookings" className="text-link">View all <Icon name="arrow" size={15} /></Link></div><div className="arrival-list">{live.arrivals.length ? live.arrivals.map((arrival: any, index: number) => { const initials = arrival.guest_full_name.split(' ').map((part: string) => part[0]).slice(0, 2).join('').toUpperCase(); return <div className="arrival-row" key={arrival.confirmation_code}><div className={`guest-avatar ${['rose', 'blue', 'gold', 'green'][index % 4]}`}>{initials}</div><div className="guest-info"><strong>{arrival.guest_full_name}</strong><span>{arrival.room_type_name} · {arrival.confirmation_code}</span></div><span className={`status ${arrival.status}`}>{arrival.status === 'confirmed' ? 'Confirmed' : 'Pending'}</span><button className="row-more" aria-label={`More actions for ${arrival.guest_full_name}`}><Icon name="more" size={16} /></button></div>; }) : <p className="empty-state">No arrivals recorded for today.</p>}</div><Link className="panel-footer-link" href="/admin/bookings">Open arrivals board <Icon name="arrow" size={15} /></Link></section>
      <section className="panel occupancy-panel"><div className="panel-heading"><div><h2>Occupancy by room type</h2><p>Current inventory utilization</p></div><span className="live-chip">Live</span></div><div className="inventory-list">{live.roomTypes.map((room: any) => { const occupied = Number(room.occupied); const total = Number(room.total_rooms); const percent = total ? Math.round(occupied / total * 100) : 0; return <div className="inventory-row" key={room.id}><div className="inventory-name"><strong>{room.name}</strong><span>{room.currency} {Number(room.base_price).toLocaleString()} / night</span></div><div className="inventory-bar"><div style={{ width: `${percent}%` }} /></div><span className="inventory-count"><b>{total - occupied}</b> available</span></div>; })}</div><div className="chart-summary"><strong>{live.occupancy}%</strong><span>Average current occupancy</span></div></section></div>
    <div className="content-grid new-booking-grid"><section className="panel"><div className="panel-heading"><div><h2>New booking requests</h2><p>Pending requests from the public booking form</p></div><Link href="/admin/bookings?status=pending" className="text-link">Review all <Icon name="arrow" size={15} /></Link></div><div className="activity-list">{live.recentBookings.length ? live.recentBookings.map((booking: any) => <Link className="activity-row booking-activity-row" href="/admin/bookings" key={booking.id}><div className="activity-icon booking"><Icon name="calendar" size={15} /></div><div><strong>{booking.guest_full_name}</strong><span>{booking.room_type_name} · {booking.confirmation_code} · {booking.guest_email}</span></div><time>{new Date(booking.created_at).toLocaleDateString()}</time></Link>) : <p className="empty-state">No new booking requests.</p>}</div></section></div>
    <div className="content-grid lower-grid"><section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Latest staff actions from the audit log</p></div></div><div className="activity-list">{live.activity.length ? live.activity.map((activity: any) => <div className="activity-row" key={`${activity.action}-${activity.created_at}`}><div className="activity-icon confirmed"><Icon name="calendar" size={15} /></div><div><strong>{activity.action}</strong><span>{activity.entity_type ?? 'System event'}</span></div><time>{new Date(activity.created_at).toLocaleDateString()}</time></div>) : <p className="empty-state">No staff activity recorded yet.</p>}</div></section><section className="panel"><div className="panel-heading"><div><h2>Team permissions</h2><p>Server-enforced access controls</p></div></div><div className="permission-note"><div className="status-dot" /><div><strong>Protected console</strong><span>Staff sessions, role checks, and audit logging are active.</span></div></div><Link className="panel-footer-link" href="/admin/settings">Review settings <Icon name="arrow" size={15} /></Link></section></div>
  </div></AdminShell>;
}
