'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function SignInPage() {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? 'Unable to sign in.'); setLoading(false); return; } router.replace('/admin'); router.refresh(); }
  return <main className="auth-page"><div className="auth-art"><div className="auth-art-glow" /><div className="auth-art-top"><div className="auth-mark">AZ</div><span>Staff console</span></div><div className="auth-art-copy"><p className="eyebrow">Abebe Zeleke International Hotel</p><h1>Every stay begins with the details.</h1><p>One calm place to care for the rooms, reservations, and people who make the hotel feel like home.</p></div><div className="auth-art-footer"><span><i /> Operations online</span><small>ADDIS ABABA · ETHIOPIA</small></div></div><div className="auth-panel"><div className="auth-form"><div className="auth-mobile-brand"><span className="auth-mark">AZ</span><strong>Abebe Zeleke</strong></div><div className="auth-form-intro"><p className="eyebrow">Welcome back</p><h2>Good to see you.</h2><p className="auth-lede">Sign in to keep today running beautifully.</p></div><form onSubmit={submit}><label>Email address<input type="email" autoComplete="username" value={email} onChange={(e) => setEmail(e.target.value)} required placeholder="name@hotel.com" /></label><label>Password<div className="password-field"><input type="password" minLength={8} autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required placeholder="8 characters minimum" /></div></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button auth-submit" disabled={loading}>{loading ? 'Opening your console…' : 'Enter operations console'}<span>→</span></button></form><p className="auth-footnote">Authorized hotel staff only · Your session is encrypted.</p></div></div></main>;
}
