'use client';

import { useEffect, useState } from 'react';
import { AdminShell } from '@/components/admin-shell';
import { Icon } from '@/components/icon';

type Inquiry = { id: string; contact_name: string; company_name: string | null; event_type: string | null; guest_count: number | null; event_date: string | null; status: string };
const statuses = ['pending', 'contacted', 'quoted', 'confirmed', 'declined', 'completed'];

export default function MeetingsPage() {
  const [inquiries, setInquiries] = useState<Inquiry[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/admin/meetings').then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setInquiries(data.inquiries); }).catch((reason) => setError(reason.message || 'Unable to load inquiries.')).finally(() => setLoading(false)); }, []);
  const visible = inquiries.filter((item) => `${item.contact_name} ${item.company_name ?? ''} ${item.event_type ?? ''}`.toLowerCase().includes(search.toLowerCase()));
  async function update(id: string, status: string) { const response = await fetch('/api/admin/meetings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); const data = await response.json(); if (!response.ok) return setError(data.error || 'Unable to update inquiry.'); setInquiries((current) => current.map((item) => item.id === id ? { ...item, status } : item)); }
  return <AdminShell><div className="page-wrap"><div className="page-heading"><div><p className="eyebrow">Events desk</p><h1>Meetings & events<span>.</span></h1><p className="lede">Turn every event request into a clear next step for the team.</p></div><button className="primary-button" onClick={() => setError('New inquiries are received through the public inquiry endpoint.') }><Icon name="plus" size={17} /> New inquiry</button></div><section className="panel table-panel"><div className="table-toolbar"><div className="filter-tabs"><span className="filter active">{inquiries.length} live inquiries</span></div><div className="table-actions"><input className="admin-search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search inquiries" aria-label="Search inquiries" /></div></div>{error && <p className="form-error admin-inline-error" role="alert">{error}</p>}<div className="table-scroll"><table><thead><tr><th>Inquiry</th><th>Organization</th><th>Event</th><th>Guests</th><th>Event date</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={6}>Loading inquiries…</td></tr> : visible.length === 0 ? <tr><td colSpan={6}>No inquiries found.</td></tr> : visible.map((inquiry) => <tr key={inquiry.id}><td><strong className="booking-code">{inquiry.id.slice(0, 8)}</strong><br />{inquiry.contact_name}</td><td>{inquiry.company_name || '—'}</td><td>{inquiry.event_type || 'Event inquiry'}</td><td>{inquiry.guest_count ?? '—'}</td><td>{inquiry.event_date || 'To be confirmed'}</td><td><select className="row-action-select" value={inquiry.status} onChange={(event) => update(inquiry.id, event.target.value)} aria-label={`Update inquiry for ${inquiry.contact_name}`}>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></section></div></AdminShell>;
}
