'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { AdminShell } from '@/components/admin-shell';
import { Icon } from '@/components/icon';

type Booking = { id: string; confirmation_code: string; guest_full_name: string; room_type_name: string; check_in: string; check_out: string; guests_count: number; status: string };
const labels: Record<string, string> = { pending: 'Pending', confirmed: 'Confirmed', completed: 'Completed', cancelled: 'Cancelled', no_show: 'No show' };

export default function BookingsPage() {
  const [bookings, setBookings] = useState<Booking[]>([]); const [status, setStatus] = useState('all'); const [search, setSearch] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const pageSize = 10; const pages = Math.max(1, Math.ceil(total / pageSize));
  const query = useMemo(() => new URLSearchParams({ status, page: String(page), pageSize: String(pageSize), ...(search ? { search } : {}), ...(from ? { from } : {}), ...(to ? { to } : {}) }), [status, page, search, from, to]);
  useEffect(() => { const controller = new AbortController(); setLoading(true); fetch(`/api/admin/bookings?${query}`, { signal: controller.signal }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setBookings(data.bookings); setTotal(data.total); setError(''); }).catch((reason) => { if (reason.name !== 'AbortError') setError(reason.message || 'Unable to load bookings.'); }).finally(() => setLoading(false)); return () => controller.abort(); }, [query]);
  async function updateStatus(id: string, nextStatus: string) { const response = await fetch(`/api/admin/bookings/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: nextStatus }) }); const data = await response.json(); if (!response.ok) return setError(data.error || 'Unable to update booking.'); setBookings((current) => current.map((booking) => booking.id === id ? { ...booking, status: nextStatus } : booking)); }
  function setFilter(next: string) { setStatus(next); setPage(1); }
  return <AdminShell><div className="page-wrap"><div className="page-heading"><div><p className="eyebrow">Reservations</p><h1>Bookings<span>.</span></h1><p className="lede">Track arrivals, stays, and guest requests in one place.</p></div><Link href="/admin/bookings?new=true" className="primary-button"><Icon name="plus" size={17} /> New booking</Link></div><section className="panel table-panel"><div className="table-toolbar"><div className="filter-tabs">{[['all', 'All bookings'], ['pending', 'Pending'], ['confirmed', 'Confirmed']].map(([value, label]) => <button className={`filter ${status === value ? 'active' : ''}`} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div><div className="table-actions"><input className="admin-search-input" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search guest or code" aria-label="Search bookings" /><label className="date-filter">From <input type="date" value={from} onChange={(event) => { setFrom(event.target.value); setPage(1); }} /></label><label className="date-filter">To <input type="date" value={to} onChange={(event) => { setTo(event.target.value); setPage(1); }} /></label></div></div>{error && <p className="form-error admin-inline-error" role="alert">{error}</p>}<div className="table-scroll"><table><thead><tr><th>Booking</th><th>Guest</th><th>Room type</th><th>Stay dates</th><th>Guests</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={7}>Loading bookings…</td></tr> : bookings.length === 0 ? <tr><td colSpan={7}>No bookings match these filters.</td></tr> : bookings.map((booking) => <tr key={booking.id}><td><strong className="booking-code">{booking.confirmation_code}</strong></td><td>{booking.guest_full_name}</td><td>{booking.room_type_name}</td><td>{booking.check_in} — {booking.check_out}</td><td>{booking.guests_count}</td><td><span className={`status ${booking.status.replace('_', '-')}`}>{labels[booking.status] ?? booking.status}</span></td><td><select className="row-action-select" aria-label={`Update ${booking.confirmation_code}`} value={booking.status} onChange={(event) => updateStatus(booking.id, event.target.value)}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No show</option></select></td></tr>)}</tbody></table></div><div className="table-footer"><span>Showing {bookings.length} of {total} bookings</span><div><button className="pagination" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>←</button><span className="pagination active">{page} / {pages}</span><button className="pagination" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>→</button></div></div></section></div></AdminShell>;
}
